apiVersion: v1
kind: ConfigMap
metadata:
  name: dtps-config
data:
  SPRING_PROFILES_ACTIVE: "prod"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: dtps-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dtps
  template:
    metadata:
      labels:
        app: dtps
    spec:
      containers:
        - name: dtps-container
          image: dtps:5.0
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: dtps-config
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /api/health
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/health
              port: 8081
            initialDelaySeconds: 20
            periodSeconds: 5

---

apiVersion: v1
kind: Service
metadata:
  name: dtps-service
spec:
  type: NodePort
  selector:
    app: dtps
  ports:
    - port: 80
      targetPort: 8081
      nodePort: 30007

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: dtps-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dtps-deployment
  minReplicas: 3
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
